### ISSUE TITLE
Using Turbo.js from local static folder

### ISSUE THREAD

**Issue by reghardtp** [miguelgrinberg/turbo-flask#31] opened 2022-04-21 10:49 UTC
Hi, I am trying to run Flask-Turbo without being connected to the internet (so the CDN is inaccessible)

I see that there is an optional argument when initializing Turbo(), url.

I am trying to populate URL in the following way:

 `   {{ turbo(url="{{ url_for('static', filename='javascript/turbo.js') }}") }}`

I checked that the static file URL is correct.

However, Turbo doesn't give any errors, but also doesn't initialize.

I downloaded the Turbo.js source:

`curl https://cdn.skypack.dev/-/@hotwired/turbo@v7.1.0-RBjb2wnkmosSQVoP27jT/dist=es2020,min/@hotwired/turbo.js --output turbo.js`

And put the output js file in static/javascript

Thanks!

**Comment by miguelgrinberg** [comment] 2022-04-21 10:54
Duplicate of https://github.com/miguelgrinberg/turbo-flask/issues/26

**Closed by miguelgrinberg** 2022-04-21 10:54 UTC

**Comment by reghardtp** [comment] 2022-04-21 11:37
Apologies for not seeing the other issue. Thanks for the quick response!
